### ISSUE TITLE
Hardware: List the updates and improvements

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/ttc2#1]
- Apply the SpaceLab standard to the schematics and the layout
    - Improve labels
    - Improve the debug pins
    - Add status leds
    - Add version resistors
    - Fix footprints and components
- Add the TX pin to the EPS communication bus
- Change the RF connectors by the through-hole version
- Add a second microcontroller to control the downlink/uplink radio module
- Change the MSP430 microcontroller by a version with FRAM memory
- Add buffer to the communication buses
- Add more optional signals to the PC-104 bus
- Add voltage/current sensors (uC and radio modules)
- Add a CAN bus
- Isolate the SPI bus of the radio modules

**Comment by andrempmattos** [comment]
**Done:**
- Apply the SpaceLab standard to the schematics and the layout
    - Improve labels
    - Improve the debug pins
    - Add status leds
    - Add version resistors
    - Fix footprints and components
- Add the TX pin to the EPS communication bus
- Change the RF connectors by the through-hole version
- Add a second microcontroller to control the downlink/uplink radio module
- Add buffer to the communication buses **(only for the antenna interface)**
- Add more optional signals to the PC-104 bus
- Add voltage/current sensors (uC and radio modules)

**Not planned for this version:**
- Change the MSP430 microcontroller by a version with FRAM memory
- Add a CAN bus
- Isolate the SPI bus of the radio modules
