### ISSUE TITLE
Hardware: Fix the label of the "Fault" and "System" LEDs

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/ttc2#113]
![Screenshot from 2023-01-11 00-03-17](https://user-images.githubusercontent.com/5316364/211708236-9fce4855-37ac-4406-ba0c-1c93043a9e58.png)
![Screenshot from 2023-01-11 00-04-16](https://user-images.githubusercontent.com/5316364/211708302-cf308576-c9b3-45ae-9889-06bf18388cbc.png)

**Comment by miguelboing** [comment]
This issue was solved through a firmware gpio inversion.
