### ISSUE TITLE
Firmware: Develop a "power sensor" device

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/ttc2#20]

**Comment by miguelboing** [comment]
Power Sensor Battery Test:

- [ ] Initialize power sensor (power_sensor_init());
- [ ] Check read individual function (try both scales, try both devices);
- [ ] Check read function (both devices);

**Comment by miguelboing** [comment]
> Power Sensor Battery Test:
> 
>     * [x]  Initialize power sensor (power_sensor_init());
> 
>     * [x]  Check read individual function (try both scales, try both devices);
> 
>     * [x]  Check read function (both devices);

![image](https://user-images.githubusercontent.com/71512482/186230648-f8f1a589-a0ad-4ec3-bd8a-239cbca56a14.png)
