### ISSUE TITLE
Hardware: Add an interrupt pin to the SPI interfaces of the PC-104

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/ttc2#35]
With an interrupt GPIO, the slaves can signalize the master when data is ready to read.

**Comment by andrempmattos** [comment]
For each MCU, an interrupt pin was added from pin 57 (interrupt capable) to the PC-104 (H1-7 and H1-9).

RA0_SPI_OBDH_INT: (MCU0 P4.7) --> PC-104 (H1-9) [available in OBDH with interrupt capability, P1.1]
RA1_SPI_OBDH_INT: (MCU1 P4.7) --> PC-104 (H1-7) [available in OBDH with interrupt capability, P1.3]
