### ISSUE TITLE
Firmware: Add a slave mode to the SPI driver

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/ttc2#58]

**Comment by miguelboing** [comment]
The SPI interruption vectors are in conflict with the ones from UART. Probably we need to create one vector for each USCI with both SPI and UART interruptions.

**Comment by mgm8** [comment]
> The SPI interruption vectors are in conflict with the ones from UART. Probably we need to create one vector for each USCI with both SPI and UART interruptions.

As discussed, we will create a separated driver to handle all the ISR routines, as described in #85 .
