### ISSUE TITLE
Firmware: Develop the RX of the UART driver

### ISSUE THREAD

**Issue by mgm8** [spacelab-ufsc/ttc2#61]
The current implementation only handle transmissions. As one interface of the TTC is a complete UART port, the RX part of the driver must be developed:
* The [DriverLib](https://github.com/spacelab-ufsc/ttc2/tree/dev_firmware/firmware/hal) must be used to handle the internal registers of the uC;
* The reception must be implemented using interruption;
* The incoming data must be stored in an internal buffer (a fixed size buffer);
* There must be a function to access the data available in the internal buffer (from an external device or task).

**Comment by miguelboing** [comment]
**Uart Battery Test:**

1. Initialize uart (uart_init). Check the buffer initialization;
2. Enable RX interruption (uart_rx_enable);
3. Check interruption routine. See if the flags are being cleared correctly, byte is stored. Check second interruption or more interruptions;
4. Check available bytes (uart_read_available), see if they match with item 3;
5. Read buffer (uart_read) using available bytes from (uart_read_available);
6. Fill the buffer to cause overflow;
7. Clear the buffer (uart_flush). Check buffer content, head, tail, size, mtu;
8. Disable RX interruption (uart_rx_disable). Check if it is disabled sending data to the uC; 
9. Enable RX again. Check if it is working using item 3.
